### ISSUE TITLE
[Bug] Combo picker window does not pop up

### ISSUE THREAD

**Issue by zrotar** [xmichelo/Beeftext#409]
#### Expected behavior

After pressing Shift+Win+Return/Enter should appear.

#### Actual behavior

After pressing Shift+Win+Return/Enter BT icon appears in the task bar, but no combo picker window pops up. If I hover over the BT icon in the taskbar I can see the snapshot of the combo picker. If I click on the icon in the task bar it disappears.

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).

11.0

#### Operating system version (e.g Windows 10)
Edition	Windows 10 Pro Version	21H1 Installed on	‎28.‎05.‎2020 OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by xmichelo** [comment]
Thanks for reporting. I'm aware of this issue, the problem is that it happen in some rather random context. I have not yet found a way to reproduce it at will.

**Comment by domportera** [comment]
I currently have a similar situation. I just installed the app on Windows 10 for context. Activating it causes it to pop up behind other windows. Clicking on the taskbar icon and putting it in focus brings it to the front and makes it usable. I just think it's not being given focus when it's launched

**Comment by xmichelo** [comment]
Thanks for your input. I will be investigating, this is very annoying. The root cause is a 'feature' of Windows that prevent applications from 'stealing' the focus, in order to prevent invasive pop-ups installed by malware. Other applications manage to properly pop-up in any case. I'm an avid [keypihrina](https://keypirinha.com/) user, and they do a good job at displaying properly, so I know it's possible.

I will investigate potential link to the change of display configuration.

**Comment by domportera** [comment]
good luck! thanks for looking out. if you'd like another example, [PowerToys ](https://github.com/microsoft/PowerToys) does it quite nicely. They implemented it based on [this repo](https://github.com/betsegaw/windowwalker/)

**Comment by xmichelo** [comment]
Can you please test the following build? I'm not sure it fixes the issue, as I cannot reproduce it at will.

- [Beeftext-12.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/7761558/Beeftext-12.0-Installer.zip)
- [Beeftext-12.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/7761559/Beeftext-12.0-PortableEdition.zip)

**Comment by domportera** [comment]
I tested and recorded a video of my findings, including as much detail as i could think to

https://youtu.be/DYGPGkr80-E

I hope this helps! video is still processing at the time of comment, so you might wanna give it some time to be available and HD

**Comment by xmichelo** [comment]
Thanks for the very detailed video 👍 .
Regarding the position of the picker when called from the desktop, you're right, it is naively computed from the desktop geometry as seen by Qt. I can improve that. 
I'm rather surprised by the positioning on the screen with a different scaling. I have to look at how Qt handles this.
As for the window popping up below the currently active one, I still have to investigate.

**Comment by domportera** [comment]
no problem!

i mean the desktop position isn't a bit problem at all - how often are people gonna be using beeftext when renaming desktop shortcuts? maybe if they have like sticky notes on their desktop, idk

good luck! :)

**Comment by xmichelo** [comment]
Hi @domportera.

I've made some changes to the way Beeftext handle the combo picker shortcut. The conditions for Windows to allow a window to pop-up on top of other windows is [rather strict](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks), and the change I implemented could be helpful. 

The drawback of this is that this method forbids the use of the *Windows* key in a shortcut. I've made a test build, The shortcut is hard-coded: **Ctrl+Alt+Shift+Enter**. You can disable it in the preferences, but any change of the shortcut will have no effect.

Please let me know if it fixes the problem for you:
- [Beeftext-12.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/7779139/Beeftext-12.0-Installer.zip)
- [Beeftext-12.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/7779144/Beeftext-12.0-PortableEdition.zip)

PS: this build also include the for #454.

**Comment by domportera** [comment]
this seems to work right off the bat! The combo picker is consistently coming up. However, #454 doesn't seem to be fixed for me - the picker is still showing up at the center of my displays when the desktop is in focus

**Comment by xmichelo** [comment]
Good to know (except for #454). I'll work on getting the fixed properly implemented with the shortcut modifiable.
